# permissions for end users to view migrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: migration-viewer-role
rules:
- apiGroups:
  - migrations.flywayoperator.io
  resources:
  - migrations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - migrations.flywayoperator.io
  resources:
  - migrations/status
  verbs:
  - get
